// Screens ------------------
export const HOME_TAB = 'HOME_TAB';
export const HOME_SCREEN = 'HOME_SCREEN';
export const DETAILS_SCREEN = 'DETAILS_SCREEN';
export const GET_STARTED_SCREEN = 'GET_STARTED_SCREEN';
export const LOADIN_SCREEN = 'LOADING_SCREEN';
export const DONATION_SCREEN = 'DONATION_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const FAMILY_SCREEN = 'FAMILY_SCREEN';
export const FAMILY_TREE_SCREEN = 'FAMILY_TREE_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const PAYMENT_SCREEN = 'PAYMENT_SCREEN';
export const TRANSACTIONS_SCREEN = 'TRANSACTIONS_SCREEN';
export const PAYMENT_SUCESS_SCREEN = 'PAYMENT_SUCESS_SCREEN';
export const CONTACT_SCREEN = 'CONTACT_SCREEN';

// query ------------------
export const DONATIONS_QUERY = 'DONATIONS_QUERY';
